name: Docs
on:
  workflow_call:
    inputs:
      docs_tag:
        description: 'Docs will be deployed into this subfolder'
        required: true
        type: string
      dry_run:
        description: 'Do not actually deploy the docs.'
        required: false
        default: true
        type: boolean
permissions:
  contents: write
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install doxygen graphviz -y

      - name: Build with Doxygen
        run: |
          mkdir -p build/docs
          doxygen docs/Doxyfile

      - name: Deploy ${{ inputs.dry_run && '(dry run)' || '(live)' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/html
          target-folder: ${{ inputs.docs_tag }}
          dry-run: ${{ inputs.dry_run }}