name: Docs
on:
  workflow_call:
    inputs:
      docs_tag:
        description: 'Docs will be deployed into this subfolder'
        required: true
        type: string
jobs:
  build_and_deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Create output folder
        run: mkdir build

      - name: Build docs
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          config_file: docs/Doxyfile
          folder: build/docs/html
          target_folder: ${{ inputs.docs_tag }}