name: On Pull Request
run-name: "#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
on:
  pull_request:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  format:
    name: Code Format
    uses: ./.github/workflows/format.yml
  overall:
    name: Pull Request Overall Status
    if: always()
    runs-on: ubuntu-latest
    needs:
      - build
      - format
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}